// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRscJ9juIqJZLxK8VV1570jURePJpGsw4',
    appId: '1:341519975028:web:76b45bb5666e9478730721',
    messagingSenderId: '341519975028',
    projectId: 'gamevault-5bebf',
    authDomain: 'gamevault-5bebf.firebaseapp.com',
    storageBucket: 'gamevault-5bebf.firebasestorage.app',
    measurementId: 'G-YM993W3KDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvNIxLnbTNw4uadl-5DlYYwMy_LOGG99U',
    appId: '1:341519975028:android:5d2139a5bbc558ae730721',
    messagingSenderId: '341519975028',
    projectId: 'gamevault-5bebf',
    storageBucket: 'gamevault-5bebf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALiFpKV6roIFOKRgTmvNF7789_QJ04VJw',
    appId: '1:341519975028:ios:7e3ddd62a06615e9730721',
    messagingSenderId: '341519975028',
    projectId: 'gamevault-5bebf',
    storageBucket: 'gamevault-5bebf.firebasestorage.app',
    iosBundleId: 'com.example.projectflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALiFpKV6roIFOKRgTmvNF7789_QJ04VJw',
    appId: '1:341519975028:ios:7e3ddd62a06615e9730721',
    messagingSenderId: '341519975028',
    projectId: 'gamevault-5bebf',
    storageBucket: 'gamevault-5bebf.firebasestorage.app',
    iosBundleId: 'com.example.projectflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRscJ9juIqJZLxK8VV1570jURePJpGsw4',
    appId: '1:341519975028:web:f660baad37a68d29730721',
    messagingSenderId: '341519975028',
    projectId: 'gamevault-5bebf',
    authDomain: 'gamevault-5bebf.firebaseapp.com',
    storageBucket: 'gamevault-5bebf.firebasestorage.app',
    measurementId: 'G-S6WWT41WM7',
  );
}
